### PR TITLE
 Make multiple_interfaces works on branch add-rrbot-corrections.

### PR DESCRIPTION
**Pull request by olivier-stasse**
* Correct URDF macro
 * Add multiple interface commands in the README.md
 * Fix controller name for forward_command_controller_position

### CODE REVIEW

**Comment by olivier-stasse** [comment]
@destogl @bmagyar IMHO this branch should be merged as soon as possible.
They are plenty of small corrections that people are proposing that are not useful because of the needed new organization proposed by this branch.
I fixed the CI, the format, tested the multiple interface, fixed some of the README.md

I did NOT try the diff example and they are probably a lot of small typos that I missed. But it looks like that the community is willing to help. So if you agree with that I would propose to merge as soon as it is possible this the branch to master and then fix the remaining problem in master. Or make it clear to contributors to work on top of this branch. Any feedback welcome.

**Review by Karsten1987 — APPROVED** [review]

**Review by destogl — APPROVED** [review]

**Comment by olivier-stasse** [comment]
Dear @destogl thanks a lot. You are probably super busy. But the next phase is to merge your PR #76. It cannot be done without the review of somebody else than you with writing permissions on the repository.

It would be nice if @Karsten1987 could have the writing rights on this repository. If this is fine with you, if you let me have the writing right I also can help on the ros2_control_demos repo for the merging and the review. This would ease the workload on you and @bmagyar.

**Comment by bmagyar** [comment]
FYI @Karsten1987 had merge right here for a week ore more now

**Comment by olivier-stasse** [comment]
@bmagyar Thanks for letting me know.

**Pull request merged**
