### PR TITLE
adjust example 1 to use hardware_spawner.

### PR DESCRIPTION
**Pull request by mamueluth**
Example of how to use the new way of configuring/activating the hardware.
One should note however: Currently the hardware gets still activated by default (legacy support). Only workaround would be to add something like:
```yaml
controller_manager:
  ros__parameters:
    ......
    configure_components_on_start:
      - ""
    activate_components_on_start:
      - ""
```
to the `example_1/bringup/config/rrbot_controllers.yaml` file. Which I think is kind of ugly and miss leading. Would not do this as hardware_spawner prints successful activation anyways... (returns current state of hardware which is activated)

### CODE REVIEW

**Comment by christophfroehlich** [comment]
I'm not sure about the plans on this: will  the old way of activating still be possible in the future? If yes, i wouldn't make this detail to be the default of the very first example.

Another issue: Will this work with humble release too? if no -> we have to generate a humbe branch here.

**Comment by mamueluth** [comment]
I think the plan is to adjust every example. As far as I know, the old way of activating the hardware is not going to be supported anymore in the future. I don't know when this is going to happen though...
Don't see much of a burden added to the user here. The demo stays more or less the same and the only thing to realize for a user is that there is a way of activating the hw.

I don't think back porting is planned but @destogl should know more about this. You are probably right with your concerns about the humble branch.

**Comment by christophfroehlich** [comment]
I remembered #239 and tried to deactivate the hw_interface with 
``` bash
$ ros2 run controller_manager hardware_spawner DiffBot --configure
[INFO] [1682761448.258076586] [hardware_spawner]: configured component 'RRBot'. Hardware now in state: lifecycle_msgs.msg.State(id=2, label='inactive').
```
The `on_deactivate` method is called with the expected output in the terminal, but after the deactivation `read` and `write` is still called. Why? Is this an issue of this hw-interface or is this not implemented properly in ros2_control?

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
I think we should add a section on that topic in the docs as well, e.g. why and how to activate/deactivate hw components after spawning.

**Review by destogl — APPROVED** [review]

**Comment by destogl** [comment]
> The `on_deactivate` method is called with the expected output in the terminal, but after the deactivation `read` and `write` is still called. Why? Is this an issue of this hw-interface or is this not implemented properly in ros2_control?

This is a feature for now. We don't have support for configuration interfaces yes, so some time ago, we decided to make those calls also in inactive state. The reason for this is the requirement to set some configuration interface before activation. 

This issue is related to ros-controls/roadmap#51

**Comment by destogl** [comment]
> I think we should add a section on that topic in the docs as well, e.g. why and how to activate/deactivate hw components after spawning.

Yes, exactly, and also add notes about this into migration notes. I am tending toward disabling automatic activation in Iron. 
The user-base will not be huge for the moment and we have the opportunity to test it well.

**Comment by christophfroehlich** [comment]
> > The `on_deactivate` method is called with the expected output in the terminal, but after the deactivation `read` and `write` is still called. Why? Is this an issue of this hw-interface or is this not implemented properly in ros2_control?
> 
> This is a feature for now. We don't have support for configuration interfaces yes, so some time ago, we decided to make those calls also in inactive state. The reason for this is the requirement to set some configuration interface before activation.
> 
> This issue is related to [ros-controls/roadmap#51](https://github.com/ros-controls/roadmap/pull/51)

I see, this makes more sense now. Maybe we should go on with the proposal from https://github.com/ros-controls/roadmap/pull/51 because with the proposed changes of the hw component lifecycle this will get to attention (and confuse) more people.

**Comment by destogl** [comment]
Let simplify this:

```
controller_manager:
  ros__parameters:
    hardware_interface_state_after_start:
      not_loaded:
        - ""
      unconfigured:
        - "arm1"
        - "arm2"
      inactive:
        - ""
```

**Comment by destogl** [comment]
you are right! We should add this to discussion agenda and make this clear

**Comment by destogl** [comment]
we add this functionality in the multi robot examples #334

**Pull request closed without merging**
