### PR TITLE
Add rrbot corrections following review of @jordan-palacios

### PR DESCRIPTION
**Pull request by olivier-stasse**
Fix for @jordan-palacios review of PR #76 
 * Fix README.md numbering
 * Add diffrobot.rviz
 * Implements a differentiable wheel robot kinematics. (i did not understood the previous implementation) So probably this is the part that should be fixed first.
 * Fix rrbot.launch.py problem with --load-only
 
TODO: further checks probably to be done

### CODE REVIEW

**Comment by nicholaspalomo** [comment]
Hi, @olivier-stasse . Thanks for working on this. I tried running the code in the branch. I started from a clean workspace, cloned your `ros2_control_demos` repo at branch `add-rrbot-corrections` and made sure to import the repos in `ros2_control_demos.repos` before building and running.
I tried running the example, which my pull request (#103 ) was meant to address:
For starters, I tried running (after sourcing my workspace):
`ros2 launch ros2_control_demo_bringup rrbot_system_position_only_gazebo.launch.py `
This resulted in several issues:


- In `rrbot_system_position_only_gazebo.launch.py`, it looks like the the forward slash (`/`) should be removed in the `gazebo` LaunchDescription. Otherwise it will complain that no such file exists.
- Similarly, for the `base_launch` Launch Description, I had to replace:
`PythonLaunchDescriptionSource([ThisLaunchFileDir(), "/rrbot.launch.py"])`
with:
`PythonLaunchDescriptionSource([os.path.dirname(os.path.realpath(__file__)), "/rrbot.launch.py"])`


- With these changes, I can launch the code and the RViz visualization pops up. However, I get warnings of this type in the console:
```
[rviz2-5] Warning: Invalid frame ID "link1" passed to canTransform argument source_frame - frame does not exist
[rviz2-5]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
[rviz2-5] Warning: Invalid frame ID "link1" passed to canTransform argument source_frame - frame does not exist
[rviz2-5]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
[rviz2-5] Warning: Invalid frame ID "link1" passed to canTransform argument source_frame - frame does not exist
```

- Something strange I noticed is that doing a `ros2 topic echo /joint_states` reveals that the effort and the velocity entries of the `JointStates` message is being populated with NaN's.


- Most concerning perhaps is that Gazebo fails to open and instead I get a segmentation fault from `gzserver` in the terminal. :(

I'll look into this some more and continue to discuss with @Karsten1987 .

Do you not have these issues as well? Maybe there's something else incorrect with the setup of my workspace. Let me know what you think.

**Comment by olivier-stasse** [comment]
@nicholaspalomo thanks for your feedback.

> Hi, @olivier-stasse . Thanks for working on this. I tried running the code in the branch. I started from a clean workspace, cloned your `ros2_control_demos` repo at branch `add-rrbot-corrections` and made sure to import the repos in `ros2_control_demos.repos` before building and running.
> I tried running the example, which my pull request (#103 ) was meant to address:
> For starters, I tried running (after sourcing my workspace):
> `ros2 launch ros2_control_demo_bringup rrbot_system_position_only_gazebo.launch.py `
> This resulted in several issues:
> 
>     * In `rrbot_system_position_only_gazebo.launch.py`, it looks like the the forward slash (`/`) should be removed in the `gazebo` LaunchDescription. Otherwise it will complain that no such file exists.
> 
>     * Similarly, for the `base_launch` Launch Description, I had to replace:
>       `PythonLaunchDescriptionSource([ThisLaunchFileDir(), "/rrbot.launch.py"])`
>       with:
>       `PythonLaunchDescriptionSource([os.path.dirname(os.path.realpath(__file__)), "/rrbot.launch.py"])`
I will integrate this, but feel free to propose a PR on my branch.
 
>     * With these changes, I can launch the code and the RViz visualization pops up. However, I get warnings of this type in the console:
> 
> 
> ```
> [rviz2-5] Warning: Invalid frame ID "link1" passed to canTransform argument source_frame - frame does not exist
> [rviz2-5]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> [rviz2-5] Warning: Invalid frame ID "link1" passed to canTransform argument source_frame - frame does not exist
> [rviz2-5]          at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> [rviz2-5] Warning: Invalid frame ID "link1" passed to canTransform argument source_frame - frame does not exist
> ```
I had the same. To be honest I have no idea where it does come from.
 
>     * Something strange I noticed is that doing a `ros2 topic echo /joint_states` reveals that the effort and the velocity entries of the `JointStates` message is being populated with NaN's.
This is more worrying. I will try to investigate.
 
>     * Most concerning perhaps is that Gazebo fails to open and instead I get a segmentation fault from `gzserver` in the terminal. :(
Could you confirm that you are recompiling the whole ros2_control repositories from the head of masters ?
I am afraid that this branch is using some new API from the ros2_control repositories which are not released yet.
This probably includes `gazebo_ros2_control` package too. 

> I'll look into this some more and continue to discuss with @Karsten1987 .
> 
> Do you not have these issues as well? Maybe there's something else incorrect with the setup of my workspace. Let me know what you think.
Thanks again for your tests. My main feedback for you setup would be for now to try with the head of masters for the ros-controls repositories.
As mentionned by @bmagyar, what you did is the preferred way, but unfortunately it takes time to have the releases going through the quality assessment needed.

My main goal here is just to help stabilize the ros2_control_demos, your help is very much appreciated.

**Comment by olivier-stasse** [comment]
@nicholaspalomo commit 6ed3b66 fixed the references to the python files you mentionned.
Having the repository from sources prevent me to have the gazebo seg fault.
As for the velocity and the effort the controller is a position controller, so it does not touch those quantities.
As the system does not update the state information.

We however yet a problem, the gazebo pid controller seems not to be working.
I will have a look.

**Comment by olivier-stasse** [comment]
Dear @nicholaspalomo for my own failure I was on the same setup than you: gazebo_ros2_control from the binaries, and I confirm that indeed the gzserver failed. I did clone all the gazebo repository as I proposed previously and this is working.

But the current rrbot_system_position_only_gazebo.launch.py is not very informative and should have the same functional level than rrbot_system_position_only.launch.py

**Pull request merged**
