### PR TITLE
[Example 7] Full example for 6 revolute joint robot

### PR DESCRIPTION
**Pull request by pac48**
This change adds an minimal example to control a custom 6 DOF robot with ros2_control. The [README](https://github.com/pac48/ros2_control_demos/tree/full-example-tutorial/r6bot) acts as a tutorial for intermediate ROS 2 users.

### CODE REVIEW

**Comment by christophfroehlich** [comment]
@pac48 I've read the readme and ran the example successfully. Nice and detailed tutorial imho. I'd start now to port that to the structure we use inside this repository. Do you have a use case for the sub-packages? We decided to pack everything within one single example_x package, I'd also apply it to this PR?

**Comment by christophfroehlich** [comment]
@pac48 how did you create `r6bot_kinematics.gv`? This is not the default tf2_tools output? Would you like to add it to the docs, or should I delete it?

**Comment by pac48** [comment]
> r6bot_kinematics.gv

Thanks @christophfroehlich  for getting back to me about this PR. I deleted the `r6bot_kinematics.gv` file since it is not needed. I appreciate your work to make this example fit the new structure!

**Comment by christophfroehlich** [comment]
> > r6bot_kinematics.gv
> 
> Thanks @christophfroehlich for getting back to me about this PR. I deleted the `r6bot_kinematics.gv` file since it is not needed. I appreciate your work to make this example fit the new structure!

We should delete the PDF as well. I was just curious about the gv-file, was this auto-generated? 

Are you happy with the license and copyright claims? Then I'm happy to merge ;)

**Comment by pac48** [comment]
> > > r6bot_kinematics.gv
> > 
> > 
> > Thanks @christophfroehlich for getting back to me about this PR. I deleted the `r6bot_kinematics.gv` file since it is not needed. I appreciate your work to make this example fit the new structure!
> 
> We should delete the PDF as well. I was just curious about the gv-file, was this auto-generated?
> 
> Are you happy with the license and copyright claims? Then I'm happy to merge ;)

The license and copyright look fine to me. And yes, the file was auto-generated, but I don't remember exactly how since it was a while ago.

**Review by christophfroehlich — APPROVED** [review]

**Comment by christophfroehlich** [comment]
@mergifyio backport humble

**Pull request merged**
