### PR TITLE
Reactivate tests for example_15

### PR DESCRIPTION
**Pull request by christophfroehlich**
Follow-up to #540 

Re-evalute after #502 is merged.

### CODE REVIEW

**Comment by christophfroehlich** [comment]
@saikishor it seems that we have a bug or a race condition in the spawner:
There is no `rrbot_1.spawner_joint_state_broadcaster` launched, but two for rrbot_2 with the obvious error
`2: [spawner-10] [WARN] [1727282065.051104080] [rrbot_2.spawner_joint_state_broadcaster]: [93mController already loaded, skipping load_controller[0m`
When I uncomment the rrbot_2_launch [here](https://github.com/ros-controls/ros2_control_demos/blob/activate_test_15/example_15/bringup/launch/multi_controller_manager_example_two_rrbots.launch.py#L159), then the JSB for rrbot_1 is spawned as expected. Any ideas?

**Comment by saikishor** [comment]
> @saikishor it seems that we have a bug or a race condition in the spawner: There is no `rrbot_1.spawner_joint_state_broadcaster` launched, but two for rrbot_2 with the obvious error `2: [spawner-10] [WARN] [1727282065.051104080] [rrbot_2.spawner_joint_state_broadcaster]: �[93mController already loaded, skipping load_controller�[0m` When I uncomment the rrbot_2_launch [here](https://github.com/ros-controls/ros2_control_demos/blob/activate_test_15/example_15/bringup/launch/multi_controller_manager_example_two_rrbots.launch.py#L159), then the JSB for rrbot_1 is spawned as expected. Any ideas?

Ahh I believe I might know. Both the robots use the same controller manager here?

**Comment by christophfroehlich** [comment]
No, `/rrbot_1/controller_manager` vs `/rrbot_2/controller_manager`

**Comment by christophfroehlich** [comment]
The problem seemed to be the `RegisterEventHandler`. We don't need it here for the spawners (or in the demos at all?). Binary build fails until next release of ros2_control.

**Review by saikishor — APPROVED** [review]
LGTM

**Pull request merged**
