### PR TITLE
Update docker instructions

### PR DESCRIPTION
**Pull request by christophfroehlich**
Using the sphinx tabs plugin, we could improve the instructions using the docker container.

Choosing one tab switches all group-tabs at once (as known from docs.ros.org). What do you think? Did that only for example 1, but would apply the changes to the others, too.

image

### CODE REVIEW

**Review by olivier-stasse — APPROVED** [review]
LGTM and tested.
This a nice addition.
I had to battle a little bit to understand how to build the documentation in a stand-alone mode. I will try to propose a PR on control.ros.org.

The way it was tested was to modify the script ```make_help_scripts/deploy_defines``` specifying the repo and the branch

**Comment by christophfroehlich** [comment]
what was the problem with spinhx? I always clone the three subrepos manually or create symlinks into the folder.

**Comment by olivier-stasse** [comment]
I simply changed 
```
declare -A subrepo_url=( ["ros2_control"]="https://github.com/ros-controls/ros2_control" ["ros2_controllers"]="https://github.com/ros-controls/ros2_controllers" ["ros2_control_demos"]="https://github.com/ros-controls/ros2_control_demos" ["gazebo_ros2_control"]="https://github.com/ros-controls/gazebo_ros2_control" ["gz_ros2_control"]="https://github.com/ros-controls/gz_ros2_control")
declare -A subrepo_pr=( ["ros2_control"]=$ROS2_CONTROL_PR ["ros2_controllers"]=$ROS2_CONTROLLERS_PR ["ros2_control_demos"]=$ROS2_CONTROL_DEMOS_PR ["gazebo_ros2_control"]=$GAZEBO_ROS2_CONTROL_PR ["gz_ros2_control"]=$GZ_ROS2_CONTROL_PR)
```
to 
```
declare -A subrepo_url=( ["ros2_control"]="https://github.com/ros-controls/ros2_control" ["ros2_controllers"]="https://github.com/ros-controls/ros2_controllers" ["ros2_control_demos"]="https://github.com/christophfroehlich/ros2_control_demos" ["gazebo_ros2_control"]="https://github.com/ros-controls/gazebo_ros2_control" ["gz_ros2_control"]="https://github.com/ros-controls/gz_ros2_control")
declare -A subrepo_pr=( ["ros2_control"]=$ROS2_CONTROL_PR ["ros2_controllers"]=$ROS2_CONTROLLERS_PR ["ros2_control_demos"]=improved_docker_description ["gazebo_ros2_control"]=$GAZEBO_ROS2_CONTROL_PR ["gz_ros2_control"]=$GZ_ROS2_CONTROL_PR)
```
in 
```https://github.com/ros-controls/control.ros.org/blob/master/make_help_scripts/deploy_defines```

no need to clone locally the subrepos as it is done by the script.

**Review by olivier-stasse — APPROVED** [review]
LGTM - All tests are passing

**Comment by olivier-stasse** [comment]
@christophfroehlich sorry I fixed some minor issues and did this by commiting directy on your branch. Hope this is fine.

**Comment by christophfroehlich** [comment]
@mergifyio backport humble

**Pull request merged**
