### PR TITLE
Touchup Dockerfile and create a workflow building it

### PR DESCRIPTION
**Pull request by christophfroehlich**
- Apply some good practice for docker files (cleanups)
- Fix `rosdep --skip-keys`
- Create workflows to regularly build the docker image
- Remove remnant of Gazebo - PR

### CODE REVIEW

**Comment by christophfroehlich** [comment]
Maybe limiting the docker workflow to changes of [the dockerfile](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths) would be sufficient, too.

**Comment by ARK3r** [comment]
With a bunch of other dependencies, I think having a daily build would be good.

**Review by olivier-stasse — APPROVED** [review]
LGTM

**Comment by christophfroehlich** [comment]
@mergifyio backport humble

**Pull request merged**
