### PR TITLE
Fix file path in rrbot_system_multi_interface.urdf.xacro

### LINKED ISSUE #95: Multiple interfaces demo not updated
Status
-------
The current `ros2_control_demo_robot/description/rrbot_system_multi_interface.urdf.xacro` in https://github.com/ros-controls/ros2_control_demos/blob/f5e163d4e0554c1f7c3ec0fb4629ae3e2be2555d/ros2_control_demo_robot/description/rrbot_system_multi_interface.urdf.xacro#L10 points towards the wrong location of `rrbot.urdf.xacro`. It is the same for `rrbot.gazebo.xacro ` and for `rrbot.materials.xacro`

They are either in the `rrbot` or `gazebo` directories.
A PR for fixing it is under way.

### PR DESCRIPTION
**Pull request by olivier-stasse**
Fix #95

### CODE REVIEW

**Review by Karsten1987 — APPROVED** [review]
lgtm.

@bmagyar @destogl could anybody merge? I don't have merge rights here.

**Comment by olivier-stasse** [comment]
Closed in favor of #101

**Comment by destogl** [comment]
> Closed in favor of #101 

@olivier-stasse did you had opportunity to look at #76?

**Comment by olivier-stasse** [comment]
@destogl Yes thanks a lot for the work you did in #76.
I worked on top of it, and all my proposed changes are in PR #101 
Let me know if they are not atomic enough, I can split them if needed.

**Pull request closed without merging**
