### PR TITLE
Docs: Make unique headings

### PR DESCRIPTION
**Pull request by christophfroehlich**
To use [autosection labels](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#automatically-label-sections), we need unique headings within the same document.

### CODE REVIEW

**Comment by christophfroehlich** [comment]
@mergifyio backport humble

**Review by bmagyar — APPROVED** [review]

**Review by moriarty — COMMENTED** [review]
LGTM

**Comment by moriarty** [comment]
opps :laughing: I was just closing all my tabs didn't I guess I had a tab with LGTM comment

**Comment by bmagyar** [comment]
Better late than never! :D

**Pull request merged**
