### PR TITLE
Give the controller type as parameter in ctrl namespace

### PR DESCRIPTION
**Pull request by christophfroehlich**
This changes the location of declaring the controller type, which will be possible with https://github.com/ros-controls/ros2_control/pull/1502

I tried to write it consistently: 

- Controller types without parameters are declared in the controller_manager namespace (joint_state_broadcaster)
- Others are declared in the controllers' namespaces, which is considered to be best-practice from now on.

### CODE REVIEW

**Comment by saikishor** [comment]
@christophfroehlich Thanks a lot for helping :)

**Comment by christophfroehlich** [comment]
Needs https://github.com/ros-controls/ros2_control/pull/1547 to work with example_15

**Review by saikishor — APPROVED** [review]
LGTM now!

**Comment by mhubii** [comment]
> * Controller types without parameters are declared in the controller_manager namespace (joint_state_broadcaster)
> * Others are declared in the controllers' namespaces, which is considered to be best-practice from now on.

Sorry, just curious. Why is that the case?

Would it also make sense to split the parameter files into controller manager-specific configurations and controller configurations parsed by spawner? Right now, there always exists redundant information, no?

I do like the change though!

**Pull request merged**
