### PR TITLE
Install ros2_control framework from binary packages

### PR DESCRIPTION
**Pull request by christophfroehlich**
Install our dependencies from binary packages instead of building them from source.

@ARK3r I can't add you as reviewer, so please just comment here ;)

### CODE REVIEW

**Comment by christophfroehlich** [comment]
I realized now that the upstream change from #305 was not released yet with ros2_control -> our demos do not work with a ros2_control binary installation at the moment.

**Comment by ARK3r** [comment]
So is semi-binary build the least time consuming way?

**Comment by ARK3r** [comment]
I can do a test of this setup (binary install, remapping reverted) tomorrow.

**Comment by christophfroehlich** [comment]
> I can do a test of this setup (binary install, remapping reverted) tomorrow.

I already created a partial revert with #310 -> this should work once this got approved.

**Comment by christophfroehlich** [comment]
Tested now after merging #310 , works like expected.

**Review by ARK3r — APPROVED** [review]

**Comment by ARK3r** [comment]
I think this looks solid. @bmagyar or @destogl if you could push this to master, @christophfroehlich and I could go forward with updating the docs and unifying the gui bring up format.

**Review by bmagyar — APPROVED** [review]

**Comment by christophfroehlich** [comment]
@mergifyio backport humble

**Pull request merged**
