### PR TITLE
Chained controllers example

### PR DESCRIPTION
**Pull request by destogl**
To test the example, checkout the following branches and following dependencies:

ros-controls/ros2_control#667
ros-controls/ros2_controllers#318

Then, follow the instructions in README added in this PR.

### CODE REVIEW

**Review by livanov93 — APPROVED** [review]
LGTM!
Good demo with multiple levels to showcase chainable controllers.

**Review by livanov93 — DISMISSED** [review]
All instructions were executed and the results were as expected.
Nice work once again!

**Comment by christophfroehlich** [comment]
How can this be integrated? Can we merge https://github.com/ros-controls/ros2_controllers/pull/318 into master or create an example without the need for custom ros2_controllers? 

The status of https://github.com/ros-controls/ros2_controllers/pull/318 is currently broken (no tf messages, and there is a merge conflict with master which I did not investigate this further)

**Comment by destogl** [comment]
No idea, we will probably have to kill this PR and get some better examples when more controllers get chainable options

**Comment by olivier-stasse** [comment]
@christophfroehlich Maybe this PR can be closed as we already have it in example_12 ?

**Pull request closed without merging**
