### PR TITLE
Update publishing rate for example_2 in userdoc.rst

### PR DESCRIPTION
**Pull request by Pratham-Pandey**
Updated publishing rate to match with diff_drive controller update rate (as in 3rd line of [config file](https://github.com/ros-controls/ros2_control_demos/blob/master/example_2/bringup/config/diffbot_controllers.yaml)).

### CODE REVIEW

**Review by saikishor — APPROVED** [review]

**Comment by christophfroehlich** [comment]
This would not be necessary actually, the controller just uses the old command until it gets a new one :man_shrugging:

**Comment by christophfroehlich** [comment]
@mergifyio backport iron humble

**Comment by Pratham-Pandey** [comment]
> This would not be necessary actually, the controller just uses the old command until it gets a new one 🤷‍♂️

Would not this create unnecessary load(although negligible) on the system as publishing more frequently would use more resource?

**Comment by christophfroehlich** [comment]
Sorry, forget my comment. I was wrong and thought you increased the update rate. Reducing it is totally fine, there is no reason for sending this faster here.

**Pull request merged**
