### PR TITLE
Add readmes in every example folder

### PR DESCRIPTION
**Pull request by christophfroehlich**
As suggested in #261 I added a brief readme in every example folder.

### CODE REVIEW

**Review by olivier-stasse — APPROVED** [review]
Thanks a lot @christophfroehlich !
It looks good to me.

**Review by destogl — APPROVED** [review]
Thanks! Great!

What are your thoughts on adding more explanation there about examples? For example explanation from here: https://github.com/ros-controls/roadmap/blob/master/design_drafts/components_architecture_and_urdf_examples.md.

Or is it better to add this under `userdoc.rst`

**Comment by christophfroehlich** [comment]
Good idea to include more infos about that. I prefer packing all relevant information into the userdoc.rst only, because this is the one being published to _control.ros.org_

**Comment by olivier-stasse** [comment]
I agree with @christophfroehlich we should avoid duplicating information. Indicating where the information is located would be enough.

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
