### PR TITLE
correct diffdrive demo

### PR DESCRIPTION
**Pull request by Karsten1987**
fixes https://github.com/ros-controls/ros2_control_demos/issues/93

### CODE REVIEW

**Comment by matthew-reynolds** [comment]
The critical change here is the `parameter=` -> `argument=`, right? Just want to verify that the deprecated `joint_state_controller` still works fine and wasn't the cause of the issue.

**Comment by Karsten1987** [comment]
That is correct, even though I've seen a big fat "SEVERE WARNING" coming from pluginlib regarding name conflicts. So I've addressed that as well.

**Review by destogl — APPROVED** [review]
This looks good!

**Review by bmagyar — APPROVED** [review]
Ta!

**Pull request merged**
