### PR TITLE
Updated README and Gazebo example

### PR DESCRIPTION
**Pull request by nicholaspalomo**
This pull request addresses #97.

### CODE REVIEW

**Review by olivier-stasse — COMMENTED** [review]
Dear @nicholaspalomo 
I believe that it will be better if your proposal would be build over the upcoming changes on branch add-rrbot-corrections.
What do you think @destogl @bmagyar ?

**Comment by nicholaspalomo** [comment]
> Dear @nicholaspalomo
> I believe that it will be better if your proposal would be build over the upcoming changes on branch add-rrbot-corrections.
> What do you think @destogl @bmagyar ?

Sure. No problem. Would you like me to merge `add-rrbot-corrections` into my fork then and update this PR?
Thanks!

**Comment by olivier-stasse** [comment]
If @destogl and/or @bmagyar and/or @Karsten1987 (or anyone with write access on this repository) can confirm this would be probably better. The PR#76 from @destogl is clearly a needed structural improvement. I proposed some other fixes in PR#101 on this branch. But I do not have write access on this repository.

**Comment by destogl** [comment]
@nicholaspalomo the Beat would be for now to do a PR based on #76 an make PR against that branch. I can than merge it also there, or we rebase it once when #76 is merged. Thanks for your input!

**Comment by olivier-stasse** [comment]
Hi @destogl merging #76 in master would be very nice. I tried to propose some small fixes for the CI in #101 in top of #76.

**Comment by olivier-stasse** [comment]
Dear @nicholaspalomo if you start from the current state of branch add-rrbot-corrections the workflow should be working. 
I am try to push the merging of add-rrbot-corrections in master.

**Comment by bmagyar** [comment]
#76 was merged, this PR is now in conflict. Please resolve and let's see what's left ;)

**Comment by destogl** [comment]
Closing because it is obsolete.

**Pull request closed without merging**
